### ISSUE TITLE
The helper "dialog" is not defined.

### ISSUE THREAD

**Issue by fabiopaiva** [doctrine/DoctrineORMModule#361]
This problem happens in version 0.9 when i execute migrations:migrate
I changed my composer.json to 0.8.* and the error not exists

**Comment by bakura10** [comment]
I've checked that, and it appears Dialog helper is deprecated and be replaced in favour of QuestionHelper, which is what DoctrineORMModule currently does. The issue needs to be fixed in Doctrine migrations (and a PR is actually submitted: https://github.com/doctrine/migrations/pull/193).

Until this is fixed, I suggest you to use the "-n" options when doing the migrations command, this deactivate the interactive mode, and therefore bypass the need for the dialog helper.
