### ISSUE TITLE
REDACTED

### ISSUE THREAD

**Issue by Moring** [doctrine/DoctrineORMModule#463]
REDACTED

**Comment by Ocramius** [comment]
As reported in the other issue, **DO NOT** report security issues in a public issue tracker.

**Comment by Moring** [comment]
Got it, my mistake found your public email later, still new to GitHub as 
reporting platform (you think they would have a better way), will not do 
it again. --d

On 04/11/2016 02:22 PM, Marco Pivetta wrote:
> Closed #463 <https://github.com/doctrine/DoctrineORMModule/issues/463>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/doctrine/DoctrineORMModule/issues/463#event-622999482>
>

-- 
David Moring
Director
Applied Autonomics LLC
Web Services for Engagement and Impact

**Comment by Ocramius** [comment]
@Moring that's fine, it has nothing to do with github though - it's really that if you publish something that may be a security issue, everyone is affected immediately if the bug is public. Let's first look at it privately, find a fix and then release an issue for it, detailing what is broken security-wise ;-)

**Comment by Moring** [comment]
@Ocramius You are absolutely correct, I apologize.  Thank you for all of your hard work, I learn from your code every day.
