### ISSUE TITLE
Allow migration configuration per module, not globally

### ISSUE THREAD

**Issue by floriandammeyer** [doctrine/DoctrineORMModule#526]
As far as I have understood the docs, it is impossible right now to have multiple migration configurations, so all migrations have to reside in the same directory (i. e. "data/database/migrations").

I don't like that approach, because I think it conflicts with the modular nature of a Zend Framework application. In a modular application, I think each module should contain all files that this module requires to function.

A "migrations stack" would be nice, so each module could add its migration configuration on top of that stack just like the "template_path_stack" of Zend\View.

I couldn't find anything in the closed issues, so I hope this topic has not been discussed before.

**Comment by Ocramius** [comment]
Migrations are per-application, and not per-module due to the monolithic
approach taken by most apps (one db per app). You cannot really split them
up, as adding/removing modules also causes inconsistencies here. Migrations
are also catalogued by timestamp, so the merging strategy could quickly
lead to schema or data inconsistencies.
