### ISSUE TITLE
Allow usage of different entity managers in doctrine-migrations CLI Command

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [doctrine/DoctrineORMModule#537]
Using doctrine-orm-module together with doctrine-migrations and multiple database connections is currently not possible.

If I don't have an "orm_default" connection / EM / configuration / ... I cant use the CLI commands ***at all***.
"orm_default" is hardcoded in [MigrationsCommandFactory on line 60](https://github.com/doctrine/DoctrineORMModule/blob/master/src/DoctrineORMModule/Service/MigrationsCommandFactory.php#L60) and since there is no configuration for it I get this exception:
```
InvalidArgumentException: Cannot load migrations from "data/DoctrineORMModule/Migrations" because it is not a valid directory in /x/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Finder/AbstractFinder.php:38

Next Zend\ServiceManager\Exception\ServiceNotCreatedException: Service with name "doctrine.migrations_configuration.orm_default" could not be created. Reason: Cannot load migrations from "data/DoctrineORMModule/Migrations" because it is not a valid directory in /x/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:765
```

What we need is an option to choose the object manager / configuration / ... for the migrations commands. Something similar was introduced for all the other commands in PR #524 .

This issue was forked from issue https://github.com/doctrine/DoctrineORMModule/issues/97.

**Comment by TomHAnderson** [comment]
I've been thinking about this issue recently I guess knowing it was a problem.  What I've decided is we need to support migrations with an `--object-manager=doctrine.entitymanager.orm_default` command line option just as https://github.com/doctrine/DoctrineORMModule/commit/f94bb4f2fada78fa899f94397e97dd605638396b#diff-91b9c94f2f305f9007116b4acd7be06bR154 did for other console commands in this module.

To do this we'll have to restructure the configuration and I'll lean towards https://github.com/API-Skeletons/zf-doctrine-data-fixture configuration structure.

**Comment by MatthiasKuehneEllerhold** [comment]
The problem I see is, that `--object-manager` is injected from the DoctrineOrmModule into the Migrations module. But you have to use it in the Migrations module.
Basically you're using something that *may* get injected from somewhere else.

**Comment by tdutrion** [comment]
Oh! It's just the problem I had last week.

So for now, I have seen the documentation showing the [migration configuration](https://github.com/doctrine/DoctrineORMModule/blob/master/docs/migrations.md) with the `orm_default` key only.

Based on that, creating a second key with the same name as the second connection/entity manager did not work. It comes down to this [hardcoded piece of code](https://github.com/doctrine/DoctrineORMModule/blob/master/src/DoctrineORMModule/Service/MigrationsCommandFactory.php#L62).

I created a ZF module here: [doctrine module migrations multi configuration](https://github.com/tdutrion/doctrine-module-migrations-multi-configuration).

I think it requires a bit more work, but it makes `--object-manager=doctrine.entitymanager.other` working with your other connection/migration config.

I guess it would be worth converting it into a PR at some point if the maintainers are happy with the solution.

**Comment by TomHAnderson** [comment]
Here are the docs for this upcoming change.  Do they adequately describe the proposed changes?

https://github.com/TomHAnderson/DoctrineORMModule/blob/9d52504d31a447d2bbc18dd625911c07fa99c983/docs/migrations.md

**Comment by TomHAnderson** [comment]
I wrote a popular data-fixture repo for Doctrine: https://github.com/API-Skeletons/zf-doctrine-data-fixture .  I think migrations is nearly just like data-fixture in that it's also a Doctrine product but it's not Doctrine ORM.

I am leaning towards keeping the current migrations in place for this repository, thereby avoiding a major version release, and instead releasing a new module for migrations which will support multiple object managers.  If the configuration exists for the current migrations config then this module will take precedent.  If the new module is installed and configuration exists for the current config then an exception will be thrown.  

Opinions?

**Comment by TomHAnderson** [comment]
Here's a README for the beginnings of this new library:  https://github.com/TomHAnderson/zf-doctrine-migrations

**Comment by TomHAnderson** [comment]
@Ocramius @guilhermeblanco @bakura10 @gianarb @superdweebie @spiffyjr

I'm proposing a new module for Zend Framework Doctrine support.  Please chime in.

**Comment by tdutrion** [comment]
Looking at your PR on documentation, I wonder why you would need to put the full service manager alias as key rather than just the last part.

In terms of behaviour, if you look at [doctrine module migrations multi configuration](https://github.com/tdutrion/doctrine-module-migrations-multi-configuration), that's exactly what it does. If you can have a look at it, I can update it the way you want (remove php 7 specifics for instance) and make a PR on this repo.

There is no compatibility break with the current version, which makes it easy to merge.

**Comment by TomHAnderson** [comment]
@tdutrion I tried using the service manager suffix in api-skeletons/zf-doctrine-data-fixture but it's not good enough; not flexible enough.  This idea is valid but in my work with Doctrine it has shown full service manager aliases cause fewer problems.  https://github.com/tdutrion/doctrine-module-migrations-multi-configuration/blob/master/src/EventListener/MigrationConfigurationListener.php#L28 already uses fully qualified aliases.  For this part I must insist on fully qualified names with the exception of the existing orm_default must be fully qualified in code to support backwards compat.

The configuration key of `migrations_configuration` is unnecessarily long; `migrations` is adequate.

On a different note, is there value with using Zend Framework for console commands rather than using Symfony?  This is a ZF module.  I feel the use of Symfony originally was a short cut.

I'd like to use this change as an opportunity to correct the mistakes (or perceived mistakes) made in the current implementation.  Still, the listener in multi-config is elegant enough and it makes the transition to multiple configs strait-forward and avoids the idea of a new repository.


@tdutrion Let's go with your idea of a PR.  I'm going to have input on your coding standard so when you submit your PR i'll submit a PR to your branch with my corrections.  A quick note: please move the factories into the same directory/namespace as the classes they create.

**Comment by tdutrion** [comment]
I will do a PR with this code soon. Is PHP 5.6 still the target? I'll move the factories according to your comment.

`migrations_configuration` is already sort of documented ([documentation for DoctrineORMModule migrations](https://github.com/doctrine/DoctrineORMModule/blob/master/docs/migrations.md)), hence the use of that key. Should we use this to use the suffix only, and then the `migrations` config for using the full orm key? (so just use the full one in `migrations` when using a different manager, and `migrations_configuration.orm_default` when none are passed in?

Finally, regarding the Console library, the migration commands (and also any orm or fixture commands) are part of doctrine (underlying libs on which we have no control), so you will always need to use Symfony Console regardless. ZF console (the zf-campus one) would only be a wrapper to symfony console, adding an extra layer of complexity. Also, while I am a big ZF fan, Symfony Console is the de facto standard now...

**Comment by TomHAnderson** [comment]
The goal of this strategy is to not have to create a major release, so yes, PHP 5.6.

As for configuration keys, I say yes, let's transition to `migrations` and cover it in the documentation.

Thanks for the console notes.

**Comment by TomHAnderson** [comment]
@tdutrion any progress?

**Comment by tdutrion** [comment]
Still in my backlog :)

I'll work on it by the end of the week.

**Comment by JiNexus** [comment]
Any progress for this issue? I hope you will consider this as top priority. :)

**Comment by Ocramius** [comment]
This isn't high priority:

 * 99%+ of users rely on a single DB/EntityManager
 * Configuring a separate EntityManager in a factory(manually) is easy

**Comment by kmwalke** [comment]
Hey everybody.  My team is running into this issue right now.  We use multiple DBs/EntityManagers to perform imports into our system.  

Just wanted to bump it

+1

**Comment by TomHAnderson** [comment]
@kmwalke Nobody is working on this at this time.  If your team wants to continue work on it that'd be great.

**Comment by jcampbellco** [comment]
Hi @TomHAnderson, I'm on @kmwalke's team as well, I think we found a workaround for us that involves overriding the `MigrationsCommandFactory` in our Zend service manger config. I'll see if I can work up a pull request shortly. Thanks for the quick response!

**Comment by leoap** [comment]
Hello jcampbellco, did you managed to get this workaround?

**Comment by roman-nagorny** [comment]
I have two variants of the doctrine.migrations_configuration:

Firstly, my ZF3 application uses 'orm_default' key in a configuration for its own migrations
'doctrine' => [
'migrations_configuration' => [
'orm_default' => [
'directory' => 'data/migration',
'name' => 'Doctrine Database Migrations for Password Storage Application',
'namespace' => 'Migration',
'table' => 'migration',
],
],
],

Secondly, my another module from composer uses 'doctrine.migrations_configuration.selaxar_orm_entitymanager' for its own needs.

I'm trying to execute the migrations from another module via command line unsing --object-manager :
./vendor/bin/doctrine-module migrations:migrate --object-manager=doctrine.entitymanager.selaxar_orm_entitymanager

The problem is I can't execute migrations from another module. Can I execute another configuration instead of 'orm_default' settings?

There is another module:
[selaxar-lang.zip](https://github.com/doctrine/DoctrineORMModule/files/2534842/selaxar-lang.zip)

And I want to execute its migrations separately via command line. Is it possible?

**Comment by timrasche** [comment]
+1

**Comment by TomHAnderson** [comment]
Though work was done on this it was abandoned.  I recommend a new repo which works like data fixtures: https://github.com/API-Skeletons/zf-doctrine-data-fixture
