### ISSUE TITLE
Fatal error after last merged commit

### ISSUE THREAD

**Issue by tasselchof** [doctrine/DoctrineORMModule#541]
( ! ) Fatal error: Uncaught Zend\ServiceManager\Exception\ServiceNotFoundException: Unable to resolve service "DoctrineORMModule\Listener\PostCliLoadListener" to a factory; are you certain you provided it during configuration? in /home/dev/domains/***/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 697

**Comment by tdutrion** [comment]
The problem will be fixed soon. It comes from the configuration being moved to the `CliConfigurator` class, relying on the container, while `init` is used before `getConfig`.

This code will be moved to `onBootstrap` in order to fix this but requires some work on tests.

Also, you should use this lib with a specific tag rather than `dev-master` unless it's for development purpose.

**Comment by Thalles** [comment]
Good morning,
Do you can help me?
Whats the last vesion ?

**Comment by tdutrion** [comment]
The latest release is 1.15 (you can see the releases on the [release page](https://github.com/doctrine/DoctrineORMModule/releases)).

For your composer version, you should use any version of the latest major (`"~1` or `"^1"`). Please [read composer's documentation](https://getcomposer.org/doc/articles/versions.md) to find out more.

**Comment by Thalles** [comment]
Thanks!

**Comment by nitinjamdhade** [comment]
I  Have same Issue...
please suggest how to come over to it.

Fatal error: Uncaught Zend\ServiceManager\Exception\ServiceNotFoundException: Unable to resolve service "DoctrineORMModule\Listener\PostCliLoadListener" to a factory; are you certain you provided it during configuration? in /home/dev/domains/***/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 697

**Comment by TomHAnderson** [comment]
@nitinjamdhade please see the answer two above your post from @tdutrion
