### ISSUE TITLE
Transition to Laminas

### ISSUE THREAD

**Issue by marc-jangvs** [doctrine/DoctrineORMModule#598]
Now Zend made it's transition to Laminas the package need to be updated to point to the correct new packages.

**Comment by sleitz** [comment]
From GitHub's network graph I can see @axelcho is working on this issue. It would be great if you could please open a pull request so others can join in or at least see there already is ongoing effort.

**Comment by sleitz** [comment]
Somebody else opened #602 in the meantime. But I'm not sure that is going well at all.

**Comment by TomHAnderson** [comment]
@sleitz I'm the Zend/Laminas guy for Doctrine.  The PR you reference is the active PR but work stopped on that because the doctrine-laminas-hydrator and DoctrineModule took precedence.  Work on those two modules is going well and contributions have been received.

Work will begin again on this transition once DoctrineModule has a good clean release.

**Comment by marc-jangvs** [comment]
I saw that PR #603 is already merged to develop branch. Any news about when it will be released?

**Comment by TomHAnderson** [comment]
Now: https://github.com/doctrine/DoctrineORMModule/releases/tag/3.0.0

As early adopters I would sure appreciate to hear your experience.

**Comment by sleitz** [comment]
I updated most of our internal projects and did not encounter any problems with the new version of DoctrineORMModule. Plenty of other stuff depending on Zend things crashed, but I think there is light at the end of the tunnel. Thank you for the work you put in this!
