### ISSUE TITLE
Migrations for multiple object-managers are not possible

### ISSUE THREAD

**Issue by boesing** [doctrine/DoctrineORMModule#638]
Hey there,

I am actually trying to create migrations for multiple object managers.
The object manager used with `--object-manager` is not being passed to the commands.

Currently its hardcoded in [MigrationsCommandFactory](https://github.com/doctrine/DoctrineORMModule/blob/fc501480667e5768030fedb2d174c3164ecccadd/src/DoctrineORMModule/Service/MigrationsCommandFactory.php#L45).

Is there any chance to get multiple object managers supported in the migration commands?

**Comment by TomHAnderson** [comment]
I did that yesterday:  https://github.com/doctrine/DoctrineORMModule/pull/637

The PR is waiting for peer approval.  Since you've dug far enough to find where it is hard coded your comments on that PR would be appreciated.

Once the PR is approved I'll release a new version of this module then implement Migrations v3

**Comment by TomHAnderson** [comment]
Finished: https://github.com/doctrine/DoctrineORMModule/releases/tag/3.0.7
