### ISSUE TITLE
Allow usage of different entity managers/connections in CLI

### ISSUE THREAD

**Issue by Ocramius** [doctrine/DoctrineORMModule#97]
It may be interesting to provide a helper (or custom Symfony Application) that replaces the EntityManager or DBAL Connection helpers based on a provided parameter such as `--em=name_of_em_service`

**Comment by duncanfwalker** [comment]
@SwissEngine I just tried using your Doctrine-Module-Extension. It work fine when the entity manager is call from some commands but when I run a migration command (eg doctrine-module orm:schema-tool:create  --em=orm_alternative) it still just picks up the orm_default configuration. It looks to me like this is because of the following lines in DoctrineORMModule 

Is this right or have I just got my configuration wrong?

```php
        // @TODO currently hardcoded: `orm_default` should be injected
        /* @var $configuration \Doctrine\DBAL\Migrations\Configuration\Configuration */
        $configuration = $serviceLocator->get('doctrine.migrations_configuration.orm_default');
        /* @var $command \Doctrine\DBAL\Migrations\Tools\Console\Command\AbstractCommand */
        $command       = new $className;
```
https://github.com/doctrine/DoctrineORMModule/blob/master/src/DoctrineORMModule/Service/MigrationsCommandFactory.php

**Comment by bvarent** [comment]
@duncanfwalker It works for me (@SwissEngine thank you!) with migrations as well as orm:schema-tool:create. It is unfortunate that the name of the migrations_configuration for the ZF2 module (`doctrine.migrations_configuration.orm_default`) is hard coded; see the TODO in the file you quoted. However the entitymanager to be used by the migrations tool is not in said configuration. And so SwissEngine's way of overriding the 'em' in the command's helper set works here too.
Are you sure you've loaded the ZF module (`SwissEngine\Tools\Doctrine\Extension`) by adding it to the `modules` key in `config\autoload\application.config.php`? Although I think you have, given that you indicate `--em` does work with other commands.
Also make sure your alternative entitymanager is configured with its own `doctrine.connection` and `doctrine.configuration` (which in turn has its own `doctrine.driver`).

**Comment by duncanfwalker** [comment]
thanks for taking the time to explain - I will have a look this when I next
come back to that project.

**Comment by alex-patterson-webdev** [comment]
I have 4 entity managers configured, none of which are called 'orm_default'. In this cause the CLI doesn't event load.

>Zend\ServiceManager\Exception\ServiceNotCreatedException: An exception was raised while creating "doctrine.entitymanager.orm_default"; no instance returned in /home/alex/www/sites/spectrum-v1/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 946

 I cannot simply add it as an service alias as it could be any of the 4 entity managers I need.

**Comment by trylika** [comment]
this issue is almost 4 years old... any news/solutions on it except for using https://github.com/SwissEngine/Doctrine-Module-Extension ?

**Comment by TomHAnderson** [comment]
Fixed with https://github.com/doctrine/DoctrineORMModule/pull/524

**Comment by MatthiasKuehneEllerhold** [comment]
Sorry @TomHAnderson but the issue with doctrine-migrations still exist.

**Comment by TomHAnderson** [comment]
@MatthiasKuehneEllerhold thanks for chiming in.  Because you are the only one to mention doctrine-migrations specifically I can't grok what part of this bug is still at issue.  In my experience the failure to echo the commands as they are executed has been fixed.

If you are still having trouble will you please create a new ticket and explain the problem you still see.
